name: SafeShutdown
version: ${project.version}
main: net.snofox.minecraft.safeshutdown.SafeShutdown
api-version: 1.13
author: SnoFox
depend:
  - LOALib
softdepend:
  - DeadlyDisconnects
commands:
  stop:
    description: Stops the server after a number of seconds
    usage: "Usage: /<command> <seconds>"
    permission: safeshutdown.stop
    permission-message: "Imperfect permissions."